# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarme', models.CharField(max_length=100, verbose_name='Alarme')),
                ('temperatura', models.CharField(max_length=100, verbose_name='Temperatura')),
                ('ambiente_instalação', models.CharField(max_length=100, verbose_name='Ambiente de Instalação')),
                ('grau_proteção', models.CharField(max_length=100, verbose_name='Grau de Proteção')),
                ('arma_cartao_sd', models.CharField(max_length=100, verbose_name='Armazenamento Cartão SD')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucao', models.CharField(max_length=100, verbose_name='Resolução')),
                ('resolucao_eco', models.CharField(max_length=100, verbose_name='Resolução ECO')),
                ('taxa_quadros', models.CharField(max_length=100, verbose_name='Taxa de Quadros')),
                ('blc', models.CharField(max_length=100, verbose_name='BLC')),
                ('ddd_dnr', models.CharField(max_length=100, verbose_name='3D DNR')),
                ('wdr', models.CharField(max_length=100, verbose_name='WDR')),
                ('zoom_digital', models.CharField(max_length=100, verbose_name='Zoom Digital')),
            ],
        ),
        migrations.CreateModel(
            name='Mibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100, verbose_name='Sensor')),
                ('obturador', models.CharField(max_length=100, verbose_name='Obturador')),
                ('lente', models.CharField(max_length=100, verbose_name='Lente')),
                ('ang_visao', models.CharField(max_length=100, verbose_name='Angulo de Visão')),
                ('campoo_visao', models.CharField(max_length=100, verbose_name='Campo de Visão')),
                ('alcence_ir', models.CharField(max_length=100, verbose_name='Alcance IR')),
                ('dia_noite', models.CharField(max_length=100, verbose_name='Dia e Noite')),
                ('sensibilidade', models.CharField(max_length=100, verbose_name='Sensibilidade')),
                ('alcance_audio', models.CharField(max_length=100, verbose_name='Alcance de Áudio')),
                ('grau_proteção', models.CharField(max_length=100, verbose_name='Grau de Proteção')),
                ('ambiente_instalação', models.CharField(max_length=100, verbose_name='Ambiente de Instalação')),
                ('armazenamento', models.CharField(max_length=100, verbose_name='Armazenamento')),
                ('ivs', models.CharField(max_length=100, verbose_name='IVS')),
                ('ganho_altofalante', models.CharField(max_length=100, verbose_name='Ganho do Altofalante')),
                ('temperatura', models.CharField(max_length=100, verbose_name='Temperatura')),
                ('consumo', models.CharField(max_length=100, verbose_name='Consumo')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Alimentação')),
                ('comp_simnext', models.CharField(max_length=100, verbose_name='Compatibilidade SimNext')),
                ('peso', models.CharField(max_length=100, verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede_cabeada', models.CharField(max_length=100, verbose_name='Rede Cabeada')),
                ('padroes_wifi', models.CharField(max_length=100, verbose_name='Padrões Wi-Fi')),
                ('frequencia_wifi', models.CharField(max_length=100, verbose_name='Frequência Wi-Fi')),
                ('largura_banda', models.CharField(max_length=100, verbose_name='Largura de Banda')),
                ('seguranca', models.CharField(max_length=100, verbose_name='Segurança')),
                ('pot_transmissao', models.CharField(max_length=100, verbose_name='Potência de Transmissão')),
                ('taxa_transmissao', models.CharField(max_length=100, verbose_name='Taxa de Transmissão')),
                ('antena', models.CharField(max_length=100, verbose_name='Antena')),
                ('metodo_config', models.CharField(max_length=100, verbose_name='Método de Configuração')),
            ],
        ),
    ]
