# Generated by Django 4.2.2 on 2023-06-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeralSpeedDome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_focal', models.CharField(max_length=100, verbose_name='Distância Focal')),
                ('zoom_optico', models.CharField(max_length=100, verbose_name='Zoom Óptico')),
                ('zoom_digital', models.CharField(max_length=100, verbose_name='Zoom Digital')),
                ('alcance_ir', models.CharField(max_length=100, verbose_name='Alcance IR')),
                ('auto_tracking', models.CharField(max_length=100, verbose_name='Auto Tracking')),
                ('aquecedor', models.CharField(max_length=100, verbose_name='Aquecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressao', models.CharField(max_length=100, verbose_name='Compressão')),
                ('resolucao', models.CharField(max_length=100, verbose_name='Resolução')),
                ('taxa_fps', models.CharField(max_length=100, verbose_name='Taxa de FPS')),
                ('comp_luz_fundo', models.CharField(max_length=100, verbose_name='Compensação de Luz de Fundo')),
                ('dori', models.CharField(max_length=100, verbose_name='DORI')),
                ('ivs', models.CharField(max_length=100, verbose_name='IVS')),
                ('starlight', models.CharField(max_length=100, verbose_name='Starlight')),
                ('sensor', models.CharField(max_length=100, verbose_name='Sensor')),
                ('ang_visao', models.CharField(max_length=100, verbose_name='Angulo de Visão')),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100, verbose_name='Interface')),
                ('ddns', models.CharField(max_length=100, verbose_name='DDNS')),
                ('rtmp', models.CharField(max_length=100, verbose_name='RTMP')),
                ('ftp', models.CharField(max_length=100, verbose_name='FTP')),
                ('sip', models.CharField(max_length=100, verbose_name='SIP')),
                ('snmp', models.CharField(max_length=100, verbose_name='SNMP')),
                ('throughput', models.CharField(max_length=100, verbose_name='Throughput')),
                ('conexoes', models.CharField(max_length=100, verbose_name='Conexões/Aberturas de canais')),
                ('intelbras_cloud', models.CharField(max_length=100, verbose_name='Intelbras Cloud')),
                ('comp_adaptador_wireless', models.CharField(max_length=100, verbose_name='Compatibilidade com Adaptador Wireless')),
                ('poe', models.CharField(max_length=100, verbose_name='PoE')),
            ],
        ),
    ]
