# Generated by Django 4.2.2 on 2023-06-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_comparativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100, verbose_name='Sensor')),
                ('dist_focal', models.CharField(max_length=100, verbose_name='Distância Focal')),
                ('ang_visao', models.CharField(max_length=100, verbose_name='Angulo de Visão')),
                ('zoom', models.CharField(max_length=100, verbose_name='Zoom')),
                ('alcance_ir', models.CharField(max_length=100, verbose_name='Alcance IR')),
                ('resolucao', models.CharField(max_length=100, verbose_name='Resolução')),
                ('comp_luz_fundo', models.CharField(max_length=100, verbose_name='Compensação de Luz de Fundo')),
                ('interface', models.CharField(max_length=100, verbose_name='Interface')),
                ('temp', models.CharField(max_length=100, verbose_name='Temperatura')),
                ('amb_instalation', models.CharField(max_length=100, verbose_name='Ambiente de Instalação')),
                ('grau_protection', models.CharField(max_length=100, verbose_name='Grau de Proteção')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
