# Generated by Django 4.2.2 on 2023-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_comparativa', '0002_camera_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('alarme', models.CharField(max_length=100, verbose_name='Alarme')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Alimentação')),
                ('consumo', models.CharField(max_length=100, verbose_name='Consumo')),
            ],
        ),
        migrations.CreateModel(
            name='gravador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canias', models.CharField(max_length=100, verbose_name='Canais')),
                ('ivs', models.CharField(max_length=100, verbose_name='IVS')),
                ('compressao', models.CharField(max_length=100, verbose_name='Compressão')),
                ('resolucao_visu', models.CharField(max_length=100, verbose_name='Resolução de Visualização')),
                ('resolucao_repr', models.CharField(max_length=100, verbose_name='Resolução de Reprodução')),
                ('tela_add', models.CharField(max_length=100, verbose_name='Tela Adicional')),
                ('video_out', models.CharField(max_length=100, verbose_name='Saída de Vídeo')),
                ('audio', models.CharField(max_length=100, verbose_name='Áudio')),
                ('ddns', models.CharField(max_length=100, verbose_name='DDNS')),
                ('rtmp', models.CharField(max_length=100, verbose_name='RTMP')),
                ('ftp', models.CharField(max_length=100, verbose_name='FTP')),
                ('snmp', models.CharField(max_length=100, verbose_name='SNMP')),
                ('throughput', models.CharField(max_length=100, verbose_name='Throughput')),
                ('conexoes', models.CharField(max_length=100, verbose_name='Conexões/Aberturas de canais')),
                ('intelbras_cloud', models.CharField(max_length=100, verbose_name='Intelbras Cloud')),
                ('comp_adp_wireless', models.CharField(max_length=100, verbose_name='Compatibilidade com Adaptador Wireless')),
                ('quant_hds', models.CharField(max_length=100, verbose_name='Quantidade de HDs')),
                ('capacidade_hd', models.CharField(max_length=100, verbose_name='Capacidade do HD')),
                ('rec_senha', models.CharField(max_length=100, verbose_name='Recuperação de Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Mibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('sensor', models.CharField(max_length=100, verbose_name='Sensor')),
                ('obturador', models.CharField(max_length=100, verbose_name='Obturador')),
                ('lente', models.CharField(max_length=100, verbose_name='Lente')),
                ('angulo_visao', models.CharField(max_length=100, verbose_name='Angulo de Visão')),
                ('campoo_visao', models.CharField(max_length=100, verbose_name='Campo de Visão')),
                ('alcence_ir', models.CharField(max_length=100, verbose_name='Alcance IR')),
                ('dia_noite', models.CharField(max_length=100, verbose_name='Dia e Noite')),
                ('sensibilidade', models.CharField(max_length=100, verbose_name='Sensibilidade')),
                ('alcance_audio', models.CharField(max_length=100, verbose_name='Alcance de Áudio')),
                ('resolucao', models.CharField(max_length=100, verbose_name='Resolução')),
                ('resolucao_eco', models.CharField(max_length=100, verbose_name='Resolução Eco')),
                ('taxa_quadros', models.CharField(max_length=100, verbose_name='Taxa de Quadros')),
                ('blc', models.CharField(max_length=100, verbose_name='BLC')),
                ('tresd_dnr', models.CharField(max_length=100, verbose_name='3D-DNR')),
                ('wdr', models.CharField(max_length=100, verbose_name='WDR')),
                ('zoom_digit', models.CharField(max_length=100, verbose_name='Zoom Digital')),
                ('comp_audio', models.CharField(max_length=100, verbose_name='Compressão de Áudio')),
                ('comp_video', models.CharField(max_length=100, verbose_name='Compressão de Vídeo')),
                ('rede_cabeada', models.CharField(max_length=100, verbose_name='Rede Cabeada')),
                ('padroes_wifi', models.CharField(max_length=100, verbose_name='Padrões Wi-Fi')),
                ('frequencia_wifi', models.CharField(max_length=100, verbose_name='Frequência Wi-Fi')),
                ('largura_banda', models.CharField(max_length=100, verbose_name='Largura de Banda')),
                ('seguranca', models.CharField(max_length=100, verbose_name='Segurança')),
                ('pot_transmissao', models.CharField(max_length=100, verbose_name='Potência de Transmissão')),
                ('taxa_transmissao', models.CharField(max_length=100, verbose_name='Taxa de Transmissão')),
                ('antena', models.CharField(max_length=100, verbose_name='Antena')),
                ('metodo_config', models.CharField(max_length=100, verbose_name='Método de Configuração')),
                ('grau_prot', models.CharField(max_length=100, verbose_name='Grau de Proteção')),
                ('ambiente_instalacao', models.CharField(max_length=100, verbose_name='Ambiente de Instalação')),
                ('armazenamento', models.CharField(max_length=100, verbose_name='Armazenamento')),
                ('ivs', models.CharField(max_length=100, verbose_name='IVS')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Alimentação')),
                ('consumo', models.CharField(max_length=100, verbose_name='Consumo')),
                ('comp_simnext', models.CharField(max_length=100, verbose_name='Compatibilidade SimNext')),
                ('peso', models.CharField(max_length=100, verbose_name='Peso')),
            ],
        ),
    ]
