# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Alimentação')),
                ('consumo', models.CharField(max_length=100, verbose_name='Consumo')),
                ('corrente_max', models.CharField(max_length=100, verbose_name='Corrente Máxima')),
            ],
        ),
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_in', models.CharField(max_length=100, verbose_name='Entrada de sinal de vídeo')),
                ('video_out', models.CharField(max_length=100, verbose_name='Saída de sinal de vídeo')),
                ('alimentacao_camera', models.CharField(max_length=100, verbose_name='Alimentação da câmera')),
                ('compatibilidade_dados', models.CharField(max_length=100, verbose_name='Compatibilidade de dados')),
                ('compatibilidade_audio', models.CharField(max_length=100, verbose_name='Compatibilidade de áudio')),
                ('fun4p1', models.CharField(max_length=100, verbose_name='Função 4 em 1')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolos_de_video', models.CharField(max_length=100, verbose_name='Protocolos de Vídeo')),
                ('alcance_analógica', models.CharField(max_length=100, verbose_name='Alcance Analógica')),
                ('alcance_hdcvi', models.CharField(max_length=100, verbose_name='Alcance HDCVI')),
                ('alcance_hdtvi', models.CharField(max_length=100, verbose_name='Alcance HDTVI')),
                ('alcance_ahd', models.CharField(max_length=100, verbose_name='Alcance AHD')),
                ('filtro_ruido_interferência', models.CharField(max_length=100, verbose_name='Filtro de Ruído e Interferência')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBalum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eletrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_balum.eletrica', verbose_name='Eletrica')),
                ('geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_balum.geral', verbose_name='Geral')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_balum.imagem', verbose_name='Imagem')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede.rede', verbose_name='Rede')),
            ],
        ),
    ]
