# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100, verbose_name='Interface')),
            ],
        ),
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canais', models.CharField(max_length=100, verbose_name='Canais')),
                ('ips_adicionais', models.CharField(blank=True, max_length=100, null=True, verbose_name='IPs Adicionais')),
                ('modo_nvr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modo NVR')),
                ('alarme', models.CharField(max_length=100, verbose_name='Alarme')),
                ('quant_hds', models.CharField(max_length=100, verbose_name='Quantidade de HDs')),
                ('capacidade_hd', models.CharField(max_length=100, verbose_name='Capacidade do HD')),
                ('rec_senha', models.CharField(max_length=100, verbose_name='Recuperação de Senha')),
                ('consumo', models.CharField(max_length=100, verbose_name='Consumo')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Alimentação')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucao_gravacao', models.CharField(max_length=100, verbose_name='Resolução de Gravação')),
                ('resolucao_visualizacao', models.CharField(max_length=100, verbose_name='Resolução de Visualização')),
                ('tela_adicional', models.CharField(max_length=100, verbose_name='Tela Adicional')),
                ('planificacao', models.CharField(max_length=100, verbose_name='Planificação')),
                ('saida_video', models.CharField(max_length=100, verbose_name='Saída de Vídeo')),
                ('ivs', models.CharField(max_length=100, verbose_name='IVS')),
                ('compressao', models.CharField(max_length=100, verbose_name='Compressão')),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100, verbose_name='Interface')),
                ('ddns', models.CharField(max_length=100, verbose_name='DDNS')),
                ('rtmp', models.CharField(max_length=100, verbose_name='RTMP')),
                ('ftp', models.CharField(max_length=100, verbose_name='FTP')),
                ('sip', models.CharField(max_length=100, verbose_name='SIP')),
                ('snmp', models.CharField(max_length=100, verbose_name='SNMP')),
                ('throughput', models.CharField(max_length=100, verbose_name='Throughput')),
                ('conexoes', models.CharField(max_length=100, verbose_name='Conexões/Aberturas de canais')),
                ('intelbras_cloud', models.CharField(max_length=100, verbose_name='Intelbras Cloud')),
                ('comp_adaptador_wireless', models.CharField(max_length=100, verbose_name='Compatibilidade com Adaptador Wireless')),
                ('poe', models.CharField(max_length=100, verbose_name='PoE')),
            ],
        ),
        migrations.CreateModel(
            name='Gravador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravador.audio', verbose_name='Audio')),
                ('geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravador.geral', verbose_name='Geral')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravador.imagem', verbose_name='Imagem')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravador.rede', verbose_name='Rede')),
            ],
        ),
    ]
