function hideit(elemento) {
  var tb = [
    [
      "VHD1010B",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1010 B",
      "titulineo",
      "1/4” 1 MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1010BG3",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1010 B G3",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1010BG4",
      '<img class="img3" src="../HTML/img/vhd1010bg4.png">',
      "titulineo",
      "VHD 1010 B G4",
      "titulineo",
      "1/4” 1 MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1010BG5",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1010 B G5",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "60° H, 33° V",
      "Digital",
      "10m",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1010BG6",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1010 B G6",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "60° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  DWDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD1010D",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1010 D",
      "titulineo",
      "1/4” 1 MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1010DG3",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1010 D G3",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1010DG4",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1010 D G4",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "59° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1010DG5",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1010 D G5",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "60° H, 33° V",
      "Digital",
      "10m",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 160mA",
      "<1,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1010DG6",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1010 D G6",
      "titulineo",
      "1/4” 1MP CMOS",
      "3.6 mm",
      "60° H, 33° V",
      "Digital",
      "10m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  DWDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 160mA",
      "<1,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1020B",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1020 B",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm",
      "74° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 200mA",
      "<2.4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1020D",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1020 D",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm",
      "86° H, 47° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 200mA",
      "<2.4W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120B",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1120 B",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm",
      "86° H, 46° V",
      "Digital",
      "20m",
      "titulineo",
      "720p",
      "BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2.1W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1120BG2",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1120 B G2",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2.1W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1120BG3",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1120 B G3",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1120BG4",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1120 B G4",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1120BG5",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1120 B G5",
      "titulineo",
      "1/2.7” 1MP CMOS",
      "3.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1120BG6",
      '<img class="img3" src="../HTML/img/vhd1120bg6.png">',
      "titulineo",
      "VHD 1120 B G6",
      "titulineo",
      "1/2.8” 1MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD1120D",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1120 D",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm",
      "86° H, 46° V",
      "Digital",
      "20m",
      "titulineo",
      "720p",
      "BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2.1W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120DG2",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1120 D G2",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2.1W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120DG3",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1120 D G3",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120DG4",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1120 D G4",
      "titulineo",
      "1/4” 1MP CMOS",
      "2.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120DG5",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1120 D G5",
      "titulineo",
      "1/2.7” 1MP CMOS",
      "3.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 160mA",
      "<1,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1120DG6",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1120 D G6",
      "titulineo",
      "1/2.8” 1MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 160mA",
      "<1,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1130BG7",
      '<img class="img3" src="../HTML/img/vhd1120bg6.png">',
      "titulineo",
      "VHD 1130 B G7",
      "titulineo",
      "1/2.8” 1MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1220B",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1220 B",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 200mA",
      "<2,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1220BG3",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1220 B G3",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1220BG4FullHD",
      '<img class="img3" src="../HTML/img/vhd1220b.png">',
      "titulineo",
      "VHD 1220 B G4 Full HD",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 260mA",
      "<3,1W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1220BG5",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1220 B G5",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "97° H, 51° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1220BG6",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1220 B G6",
      "titulineo",
      "1/2.8” 2MP CMOS",
      "3.6 mm",
      "98° H, 51° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,28W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD1220Black",
      '<img class="img3" src="../HTML/img/vhd1220black.png">',
      "titulineo",
      "VHD 1220 Black",
      "titulineo",
      "1/2.8” 2MP CMOS",
      "3.6 mm",
      "98° H, 51° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,28W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD1220DBlack",
      '<img class="img3" src="../HTML/img/vhd1220dblack.png">',
      "titulineo",
      "VHD 1220 D Black",
      "titulineo",
      "1/2.8” 2MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 130mA",
      "<1,56W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1220DFullColor",
      '<img class="img3" src="../HTML/img/vhd1220dfc.png">',
      "titulineo",
      "VHD 1220 D Full Color",
      "titulineo",
      "1/2.8” CMOS",
      "2.8 mm",
      "112° H, 60° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 270mA",
      "<2,9W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1220DG3",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1220 D G3",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1220DG4FullHD",
      '<img class="img3" src="../HTML/img/vhd1010d.png">',
      "titulineo",
      "VHD 1220 D G4 Full HD",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "2.8 mm",
      "110° H, 60° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 260mA",
      "<3,1W",
      "-10 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1220DG5",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1220 D G5",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "2.8 mm",
      "110° H, 61° V",
      "Digital",
      "20m",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 140mA",
      "<1,5W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1220FullColor",
      '<img class="img3" src="../HTML/img/vhd1220fc.png">',
      "titulineo",
      "VHD 1220 Full Color",
      "titulineo",
      "1/2.8” CMOS",
      "3.6 mm",
      "90° H, 48° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 270mA",
      "<2,9W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1420B",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1420 B",
      "titulineo",
      "1/2.7” 4MP CMOS",
      "3.6 mm",
      "80° H, 44° V",
      "Digital",
      "20m",
      "titulineo",
      "4MP",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 325mA",
      "<3,9W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD1420BG6",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1420 B G6",
      "titulineo",
      "1/2.7” 4MP CMOS",
      "3.6 mm",
      "80° H, 44° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "4MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 325mA",
      "<3,9W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD1420D",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1420 D",
      "titulineo",
      "1/2.7” 4MP CMOS",
      "2.8 mm",
      "104° H, 58° V",
      "Digital",
      "20m",
      "titulineo",
      "4MP",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 241mA",
      "<2,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1420DG6",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1420 D G6",
      "titulineo",
      "1/2.7” 4MP CMOS",
      "2.8 mm",
      "104° H, 58° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "4MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 241mA",
      "<2,9W",
      "-40 °C a 60 °C",
      "Interno",
      "-",
    ],
    [
      "VHD1520DG7",
      '<img class="img3" src="../HTML/img/vhd1010dg5.png">',
      "titulineo",
      "VHD 1520 D G7",
      "titulineo",
      "-",
      "-",
      "-",
      "Digital",
      "-",
      "titulineo",
      "-",
      "-",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "-",
      "-",
      "-",
      "-",
      "-",
    ],
    [
      "VHD1530BG7",
      '<img class="img3" src="../HTML/img/vhd1010bg5.png">',
      "titulineo",
      "VHD 1530 B G7",
      "titulineo",
      "-",
      "-",
      "-",
      "Digital",
      "-",
      "titulineo",
      "-",
      "-",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "-",
      "-",
      "-",
      "-",
      "-",
    ],
    [
      "VHL1120B",
      '<img class="img3" src="../HTML/img/vhl1120b.png">',
      "titulineo",
      "VHL 1120 B",
      "titulineo",
      '1/2,7" 1MP CMOS',
      "3,6 mm",
      "96º H, 51º V",
      "Digital",
      "20 m",
      "titulineo",
      "1MP (720p)",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 190 mA",
      "2,2 W",
      "-40ºC a 60ºC",
      "Interno / Externo",
      "IP66",
    ],
    [
      "VHL1120D",
      '<img class="img3" src="../HTML/img/vhl1010c.png">',
      "titulineo",
      "VHL 1120 D",
      "titulineo",
      '1/2,7" 1MP CMOS',
      "3,6 mm",
      "96º H, 51º V",
      "Digital",
      "20 m",
      "titulineo",
      "1MP (720p)",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 160 mA",
      "1,9 W",
      "-40ºC a 60ºC",
      "Interno",
      "NÃO",
    ],
    [
      "VHL1220B",
      '<img class="img3" src="../HTML/img/vhl1120b.png">',
      "titulineo",
      "VHL 1220 B",
      "titulineo",
      '1/2,7" 2MP CMOS',
      "3,6 mm",
      "96º H, 51º V",
      "Digital",
      "20 m",
      "titulineo",
      "2MP (1080p)",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 190 mA",
      "2,2 W",
      "-40ºC a 60ºC",
      "Interno / Externo",
      "IP66",
    ],
    [
      "VHL1220D",
      '<img class="img3" src="../HTML/img/vhl1010c.png">',
      "titulineo",
      "VHL 1220 D",
      "titulineo",
      '1/2,7" 2MP CMOS',
      "2,8 mm",
      "108º H, 60º V",
      "Digital",
      "20 m",
      "titulineo",
      "2MP (1080p)",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 160 mA",
      "1,9 W",
      "-40ºC a 60ºC",
      "Interno",
      "NÃO",
    ],
    [
      "VHL1010D",
      '<img class="img3" src="../HTML/img/vhl1010c.png">',
      "titulineo",
      "VHL 1010 D",
      "titulineo",
      '1/4" 1MP CMOS',
      "3,6 mm",
      "60º H, 33º V",
      "Digital",
      "10 m",
      "titulineo",
      "1MP (720p)",
      "AGC / BLC / WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 160 mA",
      "1,9 W",
      "-40ºC a 60ºC",
      "Interno",
      "NÃO",
    ],
    [
      "VHC1120B",
      '<img class="img3" src="../HTML/img/vhl1120b.png">',
      "titulineo",
      "VHC 1120 B",
      "titulineo",
      '1/4" 1MP CMOS',
      "2,8 mm",
      "86º H, 48º V",
      "Digital",
      "20 m",
      "titulineo",
      "1MP (720p)",
      "AGC / BLC / WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 170 mA",
      "1,8 W",
      "-40ºC a 60ºC",
      "Interno / Externo",
      "IP66",
    ],
    [
      "VHC1120D",
      '<img class="img3" src="../HTML/img/vhl1010c.png">',
      "titulineo",
      "VHC 1120 B",
      "titulineo",
      '1/4" 1MP CMOS',
      "2,8 mm",
      "86º H, 48º V",
      "Digital",
      "20 m",
      "titulineo",
      "1MP (720p)",
      "AGC / BLC / WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12 Vdc / 170 mA",
      "1,8 W",
      "-40ºC a 60ºC",
      "Interno",
      "NÃO",
    ],

    /*Serie 3000*/
    [
      "VHD3020B",
      '<img class="img3" src="../HTML/img/vhd3020.png">',
      "titulineo",
      "VHD 3020 B",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm F-1.9",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3030B",
      '<img class="img3" src="../HTML/img/vhd3030b.png">',
      "titulineo",
      "VHD 3030 B",
      "titulineo",
      "1/2.9” 1MP CMOS",
      "3.6 mm F-1.9/6 mm F-1.9",
      "86º (H) x 46º (V) (3,6 mm)52º (H) x 28º (V) (6 mm)",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 270mA",
      "<3,3W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3030BFullHD",
      '<img class="img3" src="../HTML/img/vhd3030fhd.png">',
      "titulineo",
      "VHD 3030 B Full HD",
      "titulineo",
      "1/2.7” 2MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "30m",
      "titulineo",
      "1080p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,5W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120B",
      '<img class="img3" src="../HTML/img/vhd3020.png">',
      "titulineo",
      "VHD 3120 B",
      "titulineo",
      "1/2.9” 1 MP CMOS",
      "3.6 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      " <2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120BG2",
      '<img class="img3" src="../HTML/img/vhd3020.png">',
      "titulineo",
      "VHD 3120 B G2",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      " 86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      " <2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120B28mmG3",
      '<img class="img3" src="../HTML/img/vhd3020.png">',
      "titulineo",
      "VHD 3120 B 2.8mm G3",
      "titulineo",
      "1/3” 1 MP CMOS",
      "2.8 mm",
      "98° H, 54° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120BG3",
      '<img class="img3" src="../HTML/img/vhd3120bg3.png">',
      "titulineo",
      "VHD 3120 B G3",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120BG4",
      '<img class="img3" src="../HTML/img/vhd3120bg4.png">',
      "titulineo",
      "VHD 3120 B G4",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120BG5",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3120 B G5",
      "titulineo",
      "1/4” 1 MP CMOS",
      "3.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120BG6",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3120 B G6",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "3.6 mm",
      "98° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3120D",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3120 D",
      "titulineo",
      "1/2.9” 1 MP CMOS",
      "2.8 mm",
      "102° H, 56° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120DG2",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3120 D G2",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    
    [
      "VHD3120DG3",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3120 D G3",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120DG4",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3120 D G4",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120DG5",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3120 D G5",
      "titulineo",
      "1/2.7” 1 MP CMOS",
      "3.6 mm",
      "97° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3120DG6",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3120 D G6",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "3.6 mm",
      "98° H, 53° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3130B",
      '<img class="img3" src="../HTML/img/vhd3120bg3.png">',
      "titulineo",
      "VHD 3130 B",
      "titulineo",
      "1/4” 1 MP CMOS",
      "3.6 mm / 6 mm",
      "86º (H) x 46º (V) (3,6 mm)52º (H) x 28º (V) (6 mm)",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 270mA",
      "<3,3W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3130BG2",
      '<img class="img3" src="../HTML/img/vhd3130bg2.jpg">',
      "titulineo",
      "VHD 3130 B G2",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 270mA",
      "<3,3W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3130BG3",
      '<img class="img3" src="../HTML/img/vhd3120bg3.png">',
      "titulineo",
      "VHD 3130 B G3",
      "titulineo",
      "1/4” 1 MP CMOS",
      "2.8 mm",
      "86° H, 46° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 330mA",
      "<4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3130BG4",
      '<img class="img3" src="../HTML/img/vhd3120bg3.png">',
      "titulineo",
      "VHD 3130 B G4",
      "titulineo",
      "1/3” 1 MP CMOS",
      "3.6 mm",
      "83° H, 44° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p / 800TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<2,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3130BG5",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3130 B G5",
      "titulineo",
      "1/2.7” 1 MP CMOS",
      "3.6 mm",
      "97° H, 53° V",
      "Digital",
      "30m",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3130BG6",
      '<img class="img3" src="../HTML/img/vhd3130bg6.png">',
      "titulineo",
      "VHD 3130 B G6",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "3.6 mm",
      "98° H, 53° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3130BG7",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3130 D G7",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "3.6 mm",
      "98° H, 53° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3130DG7",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3130 D G7",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "3,6 mm",
      "98°H, 53° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1MP / 600TVL",
      "AGC / BLC / DWDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3130VF",
      '<img class="img3" src="../HTML/img/vhd3140vf.png">',
      "titulineo",
      "VHD 3130 VF",
      "titulineo",
      "1/2.9” 1 MP CMOS",
      "2,7 a 12 mm",
      "91° H, 26° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3140VF",
      '<img class="img3" src="../HTML/img/vhd3140vf.png">',
      "titulineo",
      "VHD 3140 VF",
      "titulineo",
      "1/2.9” 1 MP CMOS",
      "2,7 a 12 mm",
      "105° a 37° H, 57° a 21° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "720p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3140VFG3",
      '<img class="img3" src="../HTML/img/vhd3140vf.png">',
      "titulineo",
      "VHD 3140 VF G3",
      "titulineo",
      "1/2.9” 1 MP CMOS",
      "2,7 a 12 mm",
      "95° a 24° H, 53° a 14° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3140VFG4",
      '<img class="img3" src="../HTML/img/vhd3140vf.png">',
      "titulineo",
      "VHD 3140 VF G4",
      "titulineo",
      "1/3” 1 MP CMOS",
      "2,7 a 13,5 mm",
      "95° a 24° H, 53° a 14° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "720p / 800TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<4W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3140VFG5",
      '<img class="img3" src="../HTML/img/vhd3140vfg5.png">',
      "titulineo",
      "VHD 3140 VF G5",
      "titulineo",
      "1/2.7” 1 MP CMOS",
      "2,7 a 12 mm",
      "109° a 31° H, 58° a 18° V",
      "Digital",
      "40m",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 360mA",
      "<4,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3140VFG6",
      '<img class="img3" src="../HTML/img/vhd3140vfg5.png">',
      "titulineo",
      "VHD 3140 VF G6",
      "titulineo",
      "1/2.8” 1 MP CMOS",
      "2,7 a 12 mm",
      "109° a 33° H, 57° a 18° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "720p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 360mA",
      "<4,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3220DAG40",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3220 D A G4.0",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "102° H, 60° V",
      "Digital",
      "20m",
      "titulineo",
      "1080p",
      "AGC / BLC",
      "titulineo",
      "1 Entrada",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3220DAG6",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3220 D A G6",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "102° H, 60° V",
      "Digital",
      "20m",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "1 Entrada",
      "titulineo",
      "Não",
      "12Vdc / 210mA",
      "<2,5W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3220DFullColor",
      '<img class="img3" src="../HTML/img/vhd3220dfc.png">',
      "titulineo",
      "VHD 3220 D Full Color",
      "titulineo",
      "1/2.8” 2 MP CMOS - STARVIS™",
      "2.8 mm",
      "112° H,  60° V",
      "Digital",
      "20m( led inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 260mA",
      "<2,8W",
      "-30 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3220DG3",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3220 D G3",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 260mA",
      "<3,1W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3220DG4",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3220 D G4",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "110° H, 56° V",
      "Digital",
      "20m",
      "titulineo",
      "1080p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 200mA",
      "<2,4W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3220DG5",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3220 D G5",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,1W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3220DG6",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3220 D G6",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "2.8 mm",
      "109° H, 61° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2,04W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3220miniD",
      '<img class="img3" src="../HTML/img/vhd3220mini.png">',
      "titulineo",
      "VHD 3220 mini D",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "107° H, 59° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 220mA",
      "<1,9W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3230BG3",
      '<img class="img3" src="../HTML/img/vhd3030fhd.png">',
      "titulineo",
      "VHD 3230 B G3",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 345mA",
      "<4,1W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3230BG4",
      '<img class="img3" src="../HTML/img/vhd3120bg3.png">',
      "titulineo",
      "VHD 3230 B G4",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "3.6 mm",
      "95° H, 46° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 345mA",
      "<4,1W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3230BG5",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3230 B G5",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "3.6 mm",
      "97° H, 51° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 190mA",
      "<2,1W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3230BG6",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3230 B G6",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "3.6 mm",
      "98° H, 51° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2,04W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3230BG7",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3230 B G7",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "3.6 mm",
      "98° H, 51° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2,04W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3230DG7",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3230 D G7",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "2.8 mm",
      "110°H, 60° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 170mA",
      "<2,04W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3230DVF",
      '<img class="img3" src="../HTML/img/vip3240dz.png">',
      "titulineo",
      "VHD 3230 D VF",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2,7 a 12 mm",
      "97° a 38° H, 48° a 20° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 320mA",
      "<3,9W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66 / IK10",
    ],
    [
      "VHD3230DVFG3",
      '<img class="img3" src="../HTML/img/vip3240dz.png">',
      "titulineo",
      "VHD 3230 D VF G3",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2,7 a 12 mm",
      "98° a 40° H, 58° a 22° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 242mA",
      "<2,9W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66 / IK10",
    ],
    [
      "VHD3230DZG5",
      '<img class="img3" src="../HTML/img/vip3240dz.png">',
      "titulineo",
      "VHD 3230 D Z G5",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2,7 a 12 mm",
      "112° a 32° H, 59° a 18° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 400mA",
      "<4,8W",
      "-30 °C a 60 °C",
      "Interno / externo",
      "IP 66 / IK10",
    ],
    [
      "VHD3240FullColor",
      '<img class="img3" src="../HTML/img/vhd3240fc.png">',
      "titulineo",
      "VHD 3240 Full Color",
      "titulineo",
      "1/2.8” 2 MP CMOS - STARVIS™",
      "3.6 mm",
      "92° H, 49° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<4,1W",
      "-30 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3240FullColorG6",
      '<img class="img3" src="../HTML/img/vhd3240fc.png">',
      "titulineo",
      "VHD 3240 Full Color G6",
      "titulineo",
      "1/2.8” 2 MP CMOS - STARVIS™",
      "3.6 mm",
      "91° H, 50° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 425mA",
      "<5,1W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3240VFG4",
      '<img class="img3" src="../HTML/img/vhd3240vf.png">',
      "titulineo",
      "VHD 3240 VF G4",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2,7 a 13,5 mm",
      "105° a 28° H, 57° a 15° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 350mA",
      "<4,2W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3240VFG6",
      '<img class="img3" src="../HTML/img/vhd3240vf.png">',
      "titulineo",
      "VHD 3240 VF G6",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "2,7 a 12 mm",
      "109° a 33° H, 57° a 18° V",
      "Digital",
      "40m",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 360mA",
      "<4,3W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 67",
    ],
    [
      "VHD3240ZG5",
      '<img class="img3" src="../HTML/img/vhd3140vfg5.png">',
      "titulineo",
      "VHD 3240 Z G5",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2,7 a 12 mm",
      "99° a 32° H, 53° a 18° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 630mA",
      "<7,6W",
      "-30 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3250VFG7",
      '<img class="img3" src="../HTML/img/vhd3140vfg5.png">',
      "titulineo",
      "VHD 3250 VF G7",
      "titulineo",
      "-",
      "-",
      "-",
      "Digital",
      "-",
      "titulineo",
      "-",
      "-",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "-",
      "-",
      "-",
      "-",
      "-",
    ],
    [
      "VHD3420D",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 3420 D",
      "titulineo",
      "1/3” 4 MP CMOS",
      "2.8 mm",
      "105° H, 57° V",
      "Digital",
      "20m",
      "titulineo",
      "4MP",
      "AGC / BLC",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 260mA",
      "<3,1W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3430BG4",
      '<img class="img3" src="../HTML/img/vhd3030fhd.png">',
      "titulineo",
      "VHD 3420 D G4",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "101°H, 54° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "4MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 310mA",
      "<3,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3430BG6",
      '<img class="img3" src="../HTML/img/vhd3430.png">',
      "titulineo",
      "VHD 3420 D G6",
      "titulineo",
      "1/2.7” 2 MP CMOS",
      "2.8 mm",
      "101°H, 54° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "4MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 310mA",
      "<3,7W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD3520DG7",
      '<img class="img3" src="../HTML/img/vhd3120dg5.png">',
      "titulineo",
      "VHD 3520 D G7",
      "titulineo",
      "-",
      "-",
      "-",
      "Digital",
      "-",
      "titulineo",
      "-",
      "-",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "-",
      "-",
      "-",
      "-",
      "-",
    ],
    [
      "VHD3530BG7",
      '<img class="img3" src="../HTML/img/vhd3120g5.png">',
      "titulineo",
      "VHD 3530 B G7",
      "titulineo",
      "-",
      "-",
      "-",
      "Digital",
      "-",
      "titulineo",
      "-",
      "-",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "-",
      "-",
      "-",
      "-",
      "-",
    ],

    /*Serie 5000 */
    [
      "VHD5020D",
      '<img class="img3" src="../HTML/img/vhd3120d.png">',
      "titulineo",
      "VHD 5020 D",
      "titulineo",
      "1/3” 2 MP CMOS",
      "3.6 mm",
      "90° H, 49° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 280mA",
      "<3,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5030B",
      '<img class="img3" src="../HTML/img/vhd3030b.png">',
      "titulineo",
      "VHD 5030 B",
      "titulineo",
      "1/3” 2 MP CMOS",
      "3.6 mm",
      "90° H, 49° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 370mA",
      "<4,5W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5040VF",
      '<img class="img3" src="../HTML/img/vhd5040.png">',
      "titulineo",
      "VHD 5040 VF",
      "titulineo",
      "1/3” 2 MP CMOS",
      "2,7 a 12 mm",
      "96° a 35° H, 47° a 18° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 310mA",
      "<3,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5040VFG2",
      '<img class="img3" src="../HTML/img/vhd5040.png">',
      "titulineo",
      "VHD 5040 VF G2",
      "titulineo",
      "1/3” 2 MP CMOS",
      "2,7 a 12 mm",
      "96° a 35° H, 47° a 18° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 310mA",
      "<3,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5230DSL",
      '<img class="img3" src="../HTML/img/vip3220d.png">',
      "titulineo",
      "VHD 5230 D SL",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "2.8 mm",
      "112°H, 60° V",
      "Digital",
      "30m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<3,6W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5240BFULLCOLOR",
      '<img class="img3" src="../HTML/img/vhd3240fc.png">',
      "titulineo",
      "VHD 5240 B FULL COLOR",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "3.6 mm",
      "92°H, 49° V",
      "Digital",
      "40m",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 500mA",
      "<6W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5240BSL",
      '<img class="img3" src="../HTML/img/vhd5040.png">',
      "titulineo",
      "VHD 5240 B SL",
      "titulineo",
      "1/2.8” 2 MP CMOS",
      "3.6 mm",
      "91°H, 49° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "1080p",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 350mA",
      "<4,2W",
      "-40 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5250Z",
      '<img class="img3" src="../HTML/img/vhd5040.png">',
      "titulineo",
      "VHD 5250 Z",
      "titulineo",
      "1/2.7” 2.1 MP CMOS",
      "2,7 a 12 mm",
      "97° a 32° H, 53° a 19° V",
      "Digital",
      "50m(inteligente)",
      "titulineo",
      "1080p / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 630mA",
      "<7,5W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5820D4K",
      '<img class="img3" src="../HTML/img/vhd5820d.png">',
      "titulineo",
      "VHD 5820 D 4K",
      "titulineo",
      "1/2.7” 8 MP CMOS",
      "2.8 mm",
      "110°H, 60° V",
      "Digital",
      "20m(inteligente)",
      "titulineo",
      "8MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 300mA",
      "<3,6W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5840B4K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 5840 B 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3.6 mm",
      "92°H, 27° V",
      "Digital",
      "40m(inteligente)",
      "titulineo",
      "8MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 600mA",
      "<5,7W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD5880Z4K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 5880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],

    /*VHL*/
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],

    /*VHC*/
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
    [
      "VHD78804K",
      '<img class="img3" src="../HTML/img/vhd5840b.png">',
      "titulineo",
      "VHD 7880 Z 4K",
      "titulineo",
      "1/2” 8 MP CMOS",
      "3,7 a 11 mm",
      "120° a 45° H, 65° a 25° V",
      "3X (optico motorizado)",
      "80m(inteligente)",
      "titulineo",
      "8MP / 600TVL",
      "AGC / BLC /  HLC /  WDR",
      "titulineo",
      "Não",
      "titulineo",
      "Não",
      "12Vdc, 24Vac / 1,5A",
      "<18,4W",
      "-10 °C a 60 °C",
      "Interno / externo",
      "IP 66",
    ],
  ];
  var table = $("#tabela tr");
  var ID = $(elemento).attr("id").replace("r", "");
  if ($(elemento).is(":checked")) {
    var content = $("#" + ID).clone();
    var content2 = $("#i" + ID).clone();
    $("#texto" + ID).append(content);
    $("#indice").append(content2);
    for (var i = 0; i < tb.length; i++) {
      if (tb[i][0] == ID) {
        tb = tb[i];
      }
    }
    for (var i = 0; i < table.length; i++) {
      var row = table[i];
      if (tb[i + 1] == "titulineo") {
        $(row).find("td").attr("colspan", $(row).prev().find("td").length);
      } else {
        $(row).append('<td id="' + ID + i + '">' + tb[i + 1] + "</td>");
      }
    }
  } else {
    $("#i" + ID + " span").each(function () {
      $(elemento).html("." + $(elemento).text().split(".")[1]);
    });
    $("#texto #" + ID).remove();
    $("#texto #i" + ID).remove();
    for (var i = 0; i < tb.length; i++) {
      if (tb[i][0] == ID) {
        tb = tb[i];
      }
    }
    for (var i = 0; i < table.length; i++) {
      var row = table[i];
      if (tb[i + 1] == "titulineo") {
        $(row).find("td").attr("colspan", $(row).prev().find("td").length);
      }
      $("#" + ID + i).remove();
    }
  }
}

function labeling() {
  $(".ind1").each(function () {
    $(this).html(
      $(this).prevAll(".ind0").length + 1 + " -" + $(this).text().split("-")[1]
    );
  });
  $(".ind2").each(function () {
    $(this).html(
      $(this).parent().prevAll(".ind0").length +
        "." +
        $(this).text().split(".")[1]
    );
  });
  $(".ind3").each(function () {
    $(this).html(
      $(this).parent().prevAll(".ind0").length +
        1 +
        " -" +
        $(this).text().split("-")[1]
    );
  });
  $(".ind4").each(function () {
    $(this).html(
      $(this).parent().parent().prevAll(".ind0").length +
        1 +
        "." +
        $(this).text().split(".")[1]
    );
  });
  $(".ind5").each(function () {
    $(this).html(
      $("#indice .ind0").length + 1 + " -" + $(this).text().split("-")[1]
    );
  });
  $(".ind6").each(function () {
    $(this).html(
      $("#indice .ind0").length + 2 + " -" + $(this).text().split("-")[1]
    );
  });
  $(".ind7").each(function () {
    $(this).html(
      $("#indice .ind0").length + 3 + " -" + $(this).text().split("-")[1]
    );
  });
}

$(function () {
  $(".btn").change(function () {
    hideit($(this));
    labeling();
  });
  var widt = $("aside").css("width");
  var widt2 = $("#inputsimg2").css("width");
  var widt3 = widt.replace("px", "") / 2 - widt2.replace("px", "") / 2;
});

$("#svg").click(function () {
  $("aside").toggleClass(".active");
  if ($("aside").hasClass(".active") == false) {
    $("aside").css("transform", "translateY(-" + $("body").height() + "px)");
    $("#texto").css("display", "block");
  }
  if ($("aside").hasClass(".active") == true) {
    $("aside").css("transform", "translateY(0px)");
    setTimeout(function () {
      $("#texto").css("display", "none");
    }, 600);
  }
});

$("#inputsimg2").click(function () {
  savePDF(document.querySelector("#texto"));
});
