# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100, verbose_name='Interface')),
                ('ddns', models.CharField(max_length=100, verbose_name='DDNS')),
                ('rtmp', models.CharField(max_length=100, verbose_name='RTMP')),
                ('ftp', models.CharField(max_length=100, verbose_name='FTP')),
                ('sip', models.CharField(max_length=100, verbose_name='SIP')),
                ('snmp', models.CharField(max_length=100, verbose_name='SNMP')),
                ('throughput', models.CharField(max_length=100, verbose_name='Throughput')),
                ('conexoes', models.CharField(max_length=100, verbose_name='Conexões/Aberturas de canais')),
                ('intelbras_cloud', models.CharField(max_length=100, verbose_name='Intelbras Cloud')),
                ('comp_adaptador_wireless', models.CharField(max_length=100, verbose_name='Compatibilidade com Adaptador Wireless')),
                ('poe', models.CharField(max_length=100, verbose_name='PoE')),
            ],
        ),
    ]
